name: 'Stock exchange rate block'
bundle: stock_exchange_rate_block
api: 'http://dev.markitondemand.com/MODApis/Api/v2/Quote/jsonp?callback=myFunction&symbol='
callback: myFunction
companies:
  AAPL: Apple
  BAC: 'Bank of America'
  RIG: Transocean
  FCX: Freeport
_core:
  default_config_hash: vHhPwp9ENM_EQwd7rCpZlBwYZMWYpKi6p3GObCSFVj4
langcode: zh-hans
